---
# handlers file for bootstrap
- name: gather facts
  setup:
  become: no

- name: install software using apk
  raw: "apk update ; apk add {{ bootstrap_apk_packages }}"
  when:
    - apk.rc == 0
  register: apkresult
  changed_when:
    - "'Installing' in apkresult.stdout"
  until: apkresult is succeeded
  retries: 3

- name: install software using apt-get
  raw: "apt-get update ; apt-get -y install {{ bootstrap_apt_packages }}"
  when:
    - apt_get.rc == 0
    - zypper.rc != 0
  register: apt_getresult
  changed_when:
    - "' 0 newly installed' not in apt_getresult.stdout"
  until: apt_getresult is succeeded
  retries: 3

- name: install software using dnf
  raw: "dnf -y install {{ bootstrap_dnf_packages }}"
  when:
    - dnf.rc == 0
  register: dnfresult
  changed_when:
    - "'Nothing' not in dnfresult.stdout"
  until: dnfresult is succeeded
  retries: 3

- name: install software using emerge
  raw: "{{ bootstrap_emerge_command }}"
  when:
    - emerge.rc == 0
  register: emergeresult
  changed_when:
    - "'changed' in emergeresult.stdout"
  until: emergeresult is succeeded
  retries: 3

- name: install software using pacman
  raw: "pacman -Sy ; pacman -T {{ bootstrap_pacman_packages }} || pacman -S --noconfirm {{ bootstrap_pacman_packages }}"
  when:
    - pacman.rc == 0
  register: pacmanresult
  changed_when:
    - "' installing python' in pacmanresult.stdout"
  until: pacmanresult is succeeded
  retries: 3

- name: install software using pkg
  raw: >
    ASSUME_ALWAYS_YES=YES
    pkg install {{ bootstrap_pkg_packages }}
    ; ln -s /usr/local/bin/python /usr/bin/python
    || exit 0
  when:
    - pkg.rc == 0
  register: pkgresult
  changed_when:
    - "'Extracting python' in pkgresult.stdout"
  until: pkgresult is succeeded
  retries: 3

- name: install software using pkg_add
  raw: pkg_add -Iz {{ bootstrap_pkg_add_packages }}
  when:
    - pkg_add.rc == 0
  register: pkg_add_getresult
  changed_when:
    - "': ok' in pkg_add_getresult.stdout"
  until: pkg_add_getresult is succeeded
  retries: 3

- name: install software using yum
  raw: "yum -y install {{ bootstrap_yum_packages }}"
  when:
    - yum.rc == 0
  register: yumresult
  changed_when:
    - "'Nothing' not in yumresult.stdout"
  until: yumresult is succeeded
  retries: 3

- name: install software using zypper
  raw: "zypper -n install {{ bootstrap_zypper_packages }}"
  when:
    - zypper.rc == 0
  register: zypperresult
  changed_when:
    - "'Nothing' not in zypperresult.stdout"
  failed_when: no
  until: zypperresult is succeeded
  retries: 3
